/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TestRouteImport } from './routes/test'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AccountSummariesRouteImport } from './routes/account-summaries'
import { Route as IndexRouteImport } from './routes/index'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSummariesRoute = AccountSummariesRouteImport.update({
  id: '/account-summaries',
  path: '/account-summaries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-summaries': typeof AccountSummariesRoute
  '/accounts': typeof AccountsRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRoute
  '/test': typeof TestRoute
  '/training': typeof TrainingRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-summaries': typeof AccountSummariesRoute
  '/accounts': typeof AccountsRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRoute
  '/test': typeof TestRoute
  '/training': typeof TrainingRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-summaries': typeof AccountSummariesRoute
  '/accounts': typeof AccountsRoute
  '/categories': typeof CategoriesRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/spaces': typeof SpacesRoute
  '/test': typeof TestRoute
  '/training': typeof TrainingRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-summaries'
    | '/accounts'
    | '/categories'
    | '/import'
    | '/login'
    | '/settings'
    | '/spaces'
    | '/test'
    | '/training'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-summaries'
    | '/accounts'
    | '/categories'
    | '/import'
    | '/login'
    | '/settings'
    | '/spaces'
    | '/test'
    | '/training'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/account-summaries'
    | '/accounts'
    | '/categories'
    | '/import'
    | '/login'
    | '/settings'
    | '/spaces'
    | '/test'
    | '/training'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSummariesRoute: typeof AccountSummariesRoute
  AccountsRoute: typeof AccountsRoute
  CategoriesRoute: typeof CategoriesRoute
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SpacesRoute: typeof SpacesRoute
  TestRoute: typeof TestRoute
  TrainingRoute: typeof TrainingRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-summaries': {
      id: '/account-summaries'
      path: '/account-summaries'
      fullPath: '/account-summaries'
      preLoaderRoute: typeof AccountSummariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSummariesRoute: AccountSummariesRoute,
  AccountsRoute: AccountsRoute,
  CategoriesRoute: CategoriesRoute,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SpacesRoute: SpacesRoute,
  TestRoute: TestRoute,
  TrainingRoute: TrainingRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
